#!/usr/bin/env bash

# This is a bash script to deploy Google Analytics Beacon
# To Google App Engine & Promote it
# Version:1.0
# Author: Prasad Tengse
# Licence: MIT

gcloud app deploy --version $(git rev-parse --short HEAD) --promote
